### ISSUE TITLE
dependency errors?

### ISSUE THREAD

**Issue by krisadhi** [Fatemejamalii/E2F-Net#1]
using the requirements.txt file, im trying to run the testing code as used in the github, but there are a lot of dependency conflicts with the requirements. note, im using this in google colab, so my results might be different. here is the output of the error.

Edit: this is after 'fixing' the dependency conflicts, but i am fairly sure there is still some discrepancy with tensorflow here

<img width="1156" alt="IMG_5509" src="https://github.com/Fatemejamalii/E2F-Net/assets/90298340/41be3940-c6c9-4a23-a10f-c7f93c874cea">

**Comment by ahasanpour** [comment]
Make sure right version of tensorflow installed

**Comment by Tracy-C9** [comment]
Hi! I've recently been exploring your Project（E2F-Net）and I'm really interested in it! I've noticed that the dataset seems to be incomplete, which has created a bit of a bottleneck for me when conducting some experiments.Here is missing dataset
![E2F](https://github.com/user-attachments/assets/1306a0f2-f417-47eb-9375-9a350b11c9aa)


I completely understand that sharing datasets might involve copyright or other issues, but if it's convenient for you, I was wondering if you could possibly share the missing parts of the dataset, or at least let me know where I might be able to find them? This would be a great help for me to further explore and apply your project.

Thank you very much for your hard work and for any help you might be able to offer! Looking forward to your reply.

**Comment by Fatemejamalii** [comment]
Hi!

Thank you for bringing this to my attention and for your interest in the E2F-Net project. 🙏

It seems that the folder was accidentally removed from the drive earlier. I’m currently in the process of re-uploading the missing data, and this should be resolved by the end of today.
