### ISSUE TITLE
How to do eye crop

### ISSUE THREAD

**Issue by Oguzhanercan** [Fatemejamalii/E2F-Net#2]
I want to train the model with different dataset, how should I create masks?

**Comment by ahasanpour** [comment]
If you feel you need more information regarding generating dataset have a look at this paper https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oVOWJ5UAAAAJ&citation_for_view=oVOWJ5UAAAAJ:2osOgNQ5qMEC

**Comment by Oguzhanercan** [comment]
Thanks, I have implemented the solution.
